version: 2.1

orbs:
  ruby: circleci/ruby@1.8

node-environments: &node-environments
  NPM_CONFIG_PREFIX: '~/.npm-global'

node-global-path: &node-global-path
  run: echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV

node-restore-cache: &node-restore-cache
  restore_cache:
    keys:
      - npm-{{ arch }}

node-save-cache: &node-save-cache
  save_cache:
    key: npm-{{ arch }}
    paths:
      - ~/.npm
      - ~/.npm-global

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1-browsers
        environment:
          <<: *node-environments
    steps:
      - checkout
      - ruby/install-deps
      - *node-global-path
      - *node-restore-cache
      - run: npm install -g pa11y-ci
      - *node-save-cache
      - run: |
          bundle exec jekyll clean
          bundle exec jekyll build
          bundle exec rake spec
      - run: script/pa11y-ci
      - persist_to_workspace:
          root: .
          paths:
            - _site
  validate:
    docker:
      - image: cimg/python:3.10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - pypi-{{ checksum "/home/circleci/.pyenv/version" }}
      - run: pip install -U html5validator
      - save_cache:
          key: pypi-{{ checksum "/home/circleci/.pyenv/version" }}
          paths:
            - /home/circleci/.cache/pip
            - /home/circleci/.pyenv/versions/
            - /home/circleci/.local/lib/
      - attach_workspace:
          at: .
      - run: html5validator --Werror --also-check-css --also-check-svg --root _site/
  proof:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - ruby/install-deps
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - htmlproofer-{{ arch }}
      - run: bundle exec rake proof || true
      - save_cache:
          key: htmlproofer-{{ arch }}
          paths:
            - tmp/.htmlproofer
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - *node-global-path
      - *node-restore-cache
      - run: npm install -g gh-pages
      - *node-save-cache
      - attach_workspace:
          at: .
      - run: |
          git config user.name "$(git --no-pager show --no-patch --format='%an')"
          git config user.email "$(git --no-pager show --no-patch --format='%ae')"
      - add_ssh_keys:
          fingerprints:
            - "dc:df:dd:84:71:e8:e3:e9:65:f4:27:1d:c1:eb:41:46"
      - run:
          command: gh-pages --branch master --dist _site --message "Update to ${CIRCLE_SHA1:0:7} [ci skip]"
          environment:
            CACHE_DIR: "~/.npm-global/.cache"

workflows:
  version: 2
  build:
    jobs:
      - build
      - validate:
          requires:
            - build
      - proof:
          requires:
            - build
      - deploy:
          requires:
            - build
            - validate
          filters:
            branches:
              only: source
