#!/bin/bash
set -euo pipefail

cleanup() {
  kill -9 "$(cat jekyll.pid)"
  rm -f jekyll.pid
  rm -rf _tmp_site
}

trap 'cleanup' ERR

(bundle exec jekyll server -d _tmp_site & echo $! >&3) 3>jekyll.pid | grep -q 'Server running'
pa11y-ci --sitemap 'http://localhost:4000/sitemap.xml' \
  --sitemap-find 'https://yous.be' --sitemap-replace 'http://localhost:4000'
cleanup
