#!/bin/bash
set -euo pipefail

bundle exec jekyll clean
bundle exec jekyll build

if [ "$TEST_SUITE" == default ]; then
  bundle exec rake spec
  html5validator --Werror --also-check-css --also-check-svg --root _site/
  script/pa11y-ci
elif [ "$TEST_SUITE" == proof ]; then
  bundle exec rake proof
elif [ "$TEST_SUITE" == deploy ]; then
  :
else
  echo 'Unknown test suite.'
  exit 1
fi
