name: HTML-Proofer

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  proof:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Get run ID of CI workflow
        id: get-run-id
        run: |
          WORKFLOW="CI"
          RUN_ID="$(gh run --repo "${{ github.repository }}" list --workflow "${WORKFLOW}" --json databaseId --jq .[0].databaseId)"
          echo "Detected latest run id of ${RUN_ID} for workflow ${WORKFLOW}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          github-token: ${{ github.token }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}
      - run: |
          mkdir _site
          tar -xf artifact.tar -C _site/
      - name: Cache .htmlproofer
        uses: actions/cache@v4
        with:
          path: |
            tmp/.htmlproofer
          key: htmlproofer-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            htmlproofer-${{ runner.os }}
          save-always: true
      - run: bundle exec rake proof
