name: HTML-Proofer

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  proof:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Get run ID of CI workflow
        id: get-run-id
        run: |
          WORKFLOW="CI"
          RUN_ID="$(gh run --repo "${{ github.repository }}" list --workflow "${WORKFLOW}" --json databaseId --jq .[0].databaseId)"
          echo "Detected latest run id of ${RUN_ID} for workflow ${WORKFLOW}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Download artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: github-pages
          github-token: ${{ github.token }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}
      - name: Extract artifact
        run: |
          mkdir _site
          tar -xf artifact.tar -C _site/
      - name: Restore .htmlproofer
        id: cache-htmlproofer-restore
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            tmp/.htmlproofer
          key: htmlproofer-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            htmlproofer-${{ runner.os }}
      - run: bundle exec rake proof
      - name: Save .htmlproofer
        if: always() && steps.cache-htmlproofer-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            tmp/.htmlproofer
          key: ${{ steps.cache-htmlproofer-restore.outputs.cache-primary-key }}
